default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, text.css, 960.css, backend.css, jquery-ui/themes/cupertino/ui.all.css]

  javascripts:    [http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js, http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/jquery-ui.min.js, backend.js]

  has_layout:     true
  layout:         layout
